#!/usr/bin/env bash
#
# Sentinel installation script — interactive setup for a Docker deployment.
#
set -euo pipefail

# ---- Colors ----
if [ -t 1 ]; then
  BOLD=$(printf '\033[1m'); DIM=$(printf '\033[2m'); RESET=$(printf '\033[0m')
  RED=$(printf '\033[31m'); GREEN=$(printf '\033[32m'); YELLOW=$(printf '\033[33m'); CYAN=$(printf '\033[36m')
else
  BOLD=""; DIM=""; RESET=""; RED=""; GREEN=""; YELLOW=""; CYAN=""
fi

info()  { printf '%s\n' "$*"; }
ok()    { printf '%s✓%s %s\n' "$GREEN" "$RESET" "$*"; }
warn()  { printf '%s!%s %s\n' "$YELLOW" "$RESET" "$*"; }
err()   { printf '%s✗%s %s\n' "$RED" "$RESET" "$*" >&2; }
fatal() { err "$*"; exit 1; }

# Work from the script's directory (repo root).
cd "$(dirname "$0")"

# ---- 1. Banner ----
cat <<BANNER
${CYAN}${BOLD}
  ____             _   _            _
 / ___|  ___ _ __ | |_(_)_ __   ___| |
 \\___ \\ / _ \\ '_ \\| __| | '_ \\ / _ \\ |
  ___) |  __/ | | | |_| | | | |  __/ |
 |____/ \\___|_| |_|\\__|_|_| |_|\\___|_|
${RESET}
 ${BOLD}Sentinel Installation Script v1.0${RESET}
 ${DIM}Self-hosted uptime monitoring made easy${RESET}

BANNER

# ---- 2. Prerequisites ----
info "${BOLD}Checking prerequisites...${RESET}"

if ! command -v docker >/dev/null 2>&1; then
  fatal "Docker is not installed. Install it from https://docs.docker.com/get-docker/ and re-run."
fi
ok "Docker: $(docker --version | sed 's/,.*//')"

if docker compose version >/dev/null 2>&1; then
  COMPOSE="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE="docker-compose"
else
  fatal "Docker Compose is not installed. Install Docker Compose v2 (https://docs.docker.com/compose/install/) and re-run."
fi
ok "Docker Compose: $($COMPOSE version --short 2>/dev/null || echo present) (${COMPOSE})"

if ! command -v git >/dev/null 2>&1; then
  fatal "Git is not installed. Install git and re-run."
fi
ok "Git: $(git --version | awk '{print $3}')"

# .env overwrite guard
if [ -f .env ]; then
  warn "A .env file already exists."
  read -r -p "Overwrite existing .env? (y/N) " OVERWRITE
  case "${OVERWRITE:-n}" in
    y|Y|yes|YES) info "Overwriting .env." ;;
    *) fatal "Aborted; leaving existing .env in place." ;;
  esac
fi
echo

# ---- 3. Timezone ----
info "${BOLD}Timezone${RESET}"
TZ_DETECTED="UTC"
if command -v timedatectl >/dev/null 2>&1; then
  TZ_DETECTED=$(timedatectl show -p Timezone --value 2>/dev/null || echo UTC)
elif command -v systemsetup >/dev/null 2>&1; then
  TZ_DETECTED=$(systemsetup -gettimezone 2>/dev/null | awk '{print $NF}' || echo UTC)
fi
[ -z "$TZ_DETECTED" ] && TZ_DETECTED="UTC"
info "Detected timezone: ${BOLD}${TZ_DETECTED}${RESET}"
read -r -p "Use this timezone? Press ENTER to accept, or type a custom one: " TZ_INPUT
TIMEZONE="${TZ_INPUT:-$TZ_DETECTED}"
ok "Using timezone: ${TIMEZONE}"
echo

# ---- 4. Database password ----
info "${BOLD}Database password${RESET} ${DIM}(min 12 characters)${RESET}"
DB_PASSWORD=""
while true; do
  read -r -s -p "Enter database password: " DB_PASSWORD; echo
  if [ "${#DB_PASSWORD}" -lt 12 ]; then
    err "Password too short (${#DB_PASSWORD} chars); need at least 12. Try again."
    continue
  fi
  read -r -s -p "Confirm database password: " DB_PASSWORD2; echo
  if [ "$DB_PASSWORD" != "$DB_PASSWORD2" ]; then
    err "Passwords do not match. Try again."
    continue
  fi
  break
done
ok "Database password set."
echo

# ---- 5. JWT secret ----
info "${BOLD}Generating JWT secret...${RESET}"
if command -v openssl >/dev/null 2>&1; then
  JWT_SECRET=$(openssl rand -base64 32)
else
  JWT_SECRET=$(head -c 32 /dev/urandom | base64 2>/dev/null || date +%s%N | sha256sum | awk '{print $1}')
fi
ok "Generated JWT secret: ••••••••••••••••"
echo

# ---- 6. Optional SMTP ----
SMTP_HOST=""; SMTP_PORT="587"; SMTP_USER=""; SMTP_PASSWORD=""; SMTP_FROM=""
info "${BOLD}Email alerts (optional)${RESET}"
read -r -p "Set up email (SMTP) alerts now? (y/N) " SMTP_ANSWER
case "${SMTP_ANSWER:-n}" in
  y|Y|yes|YES)
    read -r -p "  SMTP host (e.g. smtp.gmail.com): " SMTP_HOST
    read -r -p "  SMTP port [587]: " SMTP_PORT_IN; SMTP_PORT="${SMTP_PORT_IN:-587}"
    read -r -p "  SMTP username (email): " SMTP_USER
    read -r -s -p "  SMTP password (app password): " SMTP_PASSWORD; echo
    read -r -p "  From address [${SMTP_USER}]: " SMTP_FROM_IN; SMTP_FROM="${SMTP_FROM_IN:-$SMTP_USER}"
    ok "SMTP configured for ${SMTP_HOST}."
    ;;
  *)
    info "Skipping email setup (you can add SMTP_* to .env later)."
    ;;
esac
echo

# ---- 7. Write .env ----
info "${BOLD}Writing .env...${RESET}"
cat > .env <<ENV
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

# Database
DB_PASSWORD=${DB_PASSWORD}
DB_PORT=5432

# Server
PORT=3000
ENVIRONMENT=production
LOG_LEVEL=info
TIMEZONE=${TIMEZONE}

# Authentication
JWT_SECRET=${JWT_SECRET}

# SMTP (email alerts)
SMTP_HOST=${SMTP_HOST}
SMTP_PORT=${SMTP_PORT}
SMTP_USER=${SMTP_USER}
SMTP_PASSWORD=${SMTP_PASSWORD}
SMTP_FROM=${SMTP_FROM}

# Other notification channels (optional)
SLACK_WEBHOOK_URL=
DISCORD_WEBHOOK_URL=
TELEGRAM_BOT_TOKEN=
TELEGRAM_CHAT_ID=
NTFY_URL=https://ntfy.sh
NTFY_TOPIC=
WEBHOOK_URL=

# Docker images
DOCKER_REGISTRY=ghcr.io
IMAGE_TAG=latest
ENV
chmod 600 .env
ok ".env created (permissions 600)."
echo

# ---- 8. Start services ----
info "${BOLD}Ready to launch.${RESET}"
read -r -p "Start Sentinel now with '${COMPOSE} up -d --build'? (Y/n) " START_ANSWER
case "${START_ANSWER:-y}" in
  n|N|no|NO)
    info "Skipping startup. When ready, run: ${BOLD}${COMPOSE} up -d --build${RESET}"
    ;;
  *)
    info "Building and starting containers (this may take a few minutes)..."
    $COMPOSE up -d --build
    echo
    ok "Sentinel is starting."
    info "  Web UI:   ${BOLD}http://localhost:3000${RESET}"
    info "  Backend:  http://localhost:3001/api/v1"
    info "  DB admin: http://localhost:8080 (Adminer)"
    echo
    info "First run: open the web UI and register — the first account becomes the admin."
    ;;
esac

echo
ok "Done."
